FROM python:3.11-slim
WORKDIR /app

# Install docker CLI for dood test
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_test.txt .
RUN pip install --no-cache-dir -r requirements_test.txt

# Create a place to mount scripts and backend go
RUN mkdir -p /app /backend-go-src

CMD ["python", "verify_system.py"]
